[project]
name = "jarvis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyttsx3>=2.99",
    "pyyaml>=6.0.3",
    "rapidfuzz>=3.14.1",
    "sounddevice>=0.5.2",
    "speechrecognition>=3.14.3",
    "vosk>=0.3.45",
]
